name: twilio_voice
description: Provides an interface to Twilio's Programmable Voice SDK to allow adding voice-over-IP (VoIP) calling into your Flutter applications.
version: 0.2.2
homepage: https://twilio-voice-web.web.app/
repository: https://github.com/cybex-dev/twilio_voice
issue_tracker: https://github.com/cybex-dev/twilio_voice/issues
topics:
  - twilio
  - voice
  - voip
  - call
  - phone

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  # temporarily - upgrade to js: 0.7.2 then finally js_interop:
  js: ^0.7.1
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter


flutter:
  
  plugin:
    platforms:
      android:
        package: com.twilio.twilio_voice
        pluginClass: TwilioVoicePlugin
      ios:
        pluginClass: TwilioVoicePlugin
      web:
        # As a temporary measure, the web implementation of a plugin is defined in
        # `twilio_voice_web`, but this will change soon with the migration to a federated
        # plugin structure.
        pluginClass: TwilioVoiceWeb
        fileName: _internal/twilio_voice_web.dart
      macos:
        pluginClass: TwilioVoicePlugin

